---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: acl
    spec:
      containers:
      - name: acl
        image: "dm848/srv-acl:v2.0.7"
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: acl
spec:
  ports:
  - port: 8888
  selector:
    app: acl
  type: "LoadBalancer"

