---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acl
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acl
    spec:
      containers:
        - image: "dm848/srv-acl:v1"
          imagePullPolicy: Always
          name: acl
          ports:
            - containerPort: 8888
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: acl
  namespace: "default"
  labels:
    app: acl
spec:
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888
  selector:
    app: acl
  type: "ClusterIP"
